### ISSUE TITLE
One CSS selector per line

### ISSUE THREAD

**Issue by thujone** [caresa/Rock-Trivia#12]
https://github.com/caresa/Rock-Trivia/blob/4d39a497d449bd671f49c9b7a9eab72e9d124bf9/main.css#L51

Some developers will put multiple selectors on one line, but it's more standard to put only one rule per line and to add as many newlines as there are selectors. For example:

```
#style1, #style2, #style3 {
   ...
}
```

would be better written like this:

```
#style1,
#style2,
#style3 {
  ...
}
```

**Comment by caresa** [comment]
Done
