### ISSUE TITLE
Add a space between selector and curly-brace

### ISSUE THREAD

**Issue by thujone** [caresa/Rock-Trivia#13]
https://github.com/caresa/Rock-Trivia/blob/4d39a497d449bd671f49c9b7a9eab72e9d124bf9/main.css#L65

Here and throughout the file, there ought to be a space between the CSS selector and the curly-brace that follows it. For example:

```
.red{         // bad
.red {        // good
button{     // bad
button {    // good
```

It doesn't seem like a big deal, but prospective employers that want to see code you've written make note of things like this.

It wouldn't be a bad idea to have a look at "style guides" for CSS and javascript. I highly recommend the AirBnb javascript and CSS style guides. Another good js style guide is called Idiomatic.

**Comment by caresa** [comment]
Done
