### ISSUE TITLE
General CSS selectors should be moved to the top of the file

### ISSUE THREAD

**Issue by thujone** [caresa/Rock-Trivia#14]
https://github.com/caresa/Rock-Trivia/blob/4d39a497d449bd671f49c9b7a9eab72e9d124bf9/main.css#L65

Because stylesheets are "cascading" (the "C" in "CSS"), general selectors should be moved toward the beginning of the file. For example, selectors that are just tag names are considered more general, and they should come before more specific rules. The `< button>` tag is a good example of this. The `< button>` CSS selector is very general and so it should be placed before you reference other, more-specific classes and IDs. For example, good CSS files will start with default styles for `< body>` and `< a>` and `< h1>`, `< h2>`, etcetera. After you've defined all your general rules, you can start getting more specific with classnames and IDs and compound selectors. Here, the button rules should be moved further up the file.

**Comment by caresa** [comment]
Done
